### ISSUE TITLE
redirect to 0.0.0.0

### ISSUE THREAD

**Issue by fedekrum** [MartinMueller2003/ESPixelStick#5]
Hi Martin,
Each time I press the reboot button in the admin, I get redirected to 0.0.0.0
I am using lattest from this repository but it happens with the official too.

![image](https://github.com/MartinMueller2003/ESPixelStick/assets/4470683/9e3890c8-091f-49f0-b2af-f350303cc401)

**Comment by MartinMueller2003** [comment]
I have seen this as well. Press the back button and you should be good to go. I will take a look at this after I look at a DMX output issue being reported on the ESP32 version.

**Comment by MartinMueller2003** [comment]
My latest builds are no longer going to 0.0.0.0
