### ISSUE TITLE
Slow upload, FPP Connect

### ISSUE THREAD

**Issue by joe8012** [MartinMueller2003/ESPixelStick#9]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

ci-12304517834

**Hardware Version**
Dig-Octa

**Binary release or compiled yourself?**

**Operating System (and version)**
Windows 11

**Web Browser (and version)**
Chrome

**Access Point**

**Describe the bug**
2400 pixel megatree(300 per port) upload was very slow and Xlights crashed after several minutes with the progress bar only at about 65%.  Reverted back to ci-12059322379.

**Comment by MartinMueller2003** [comment]
This reduction in throughput is intentional. The higher transfer rates resulted in SD cards locking up and requiring a power cycle to recover.

**Comment by joe8012** [comment]
I understand why the uploads are taking longer.  My point is Xlights is crashing before the uploads are completed on most of my seven controllers.  On my megatree (Octa-8 ports/300px per port) and my column matrix’s(Quad AE+ - 4 ports/468px per port) Xlights crashes when they are 40 to 50% uploaded.  After further testing the crash is exactly Five Minutes from the start of the upload.  I don’t know if xlights is timing out or there is another reason for the crash.   Out of 7 controllers, I only have one that completes the upload before the crash.  I only use 3 ports and 490 pixels on that controller.  My total show is just under 10,000 pixels.

**Comment by MartinMueller2003** [comment]
Have you reported that to the xLights team? I will take a look from my end.

**Comment by joe8012** [comment]
Not yet but I will.

**Comment by noman1228** [comment]
Your latest fixes this issue for me so far. Reset on initial upload. If you're compiling from code Joe, I can give you a few things that have helped me. None of the issues I've had end up being related to the base release firmware, instead all of my problems are a result of cheap boards not officially supported by the devs.

**Comment by joe8012** [comment]
> Your latest fixes this issue for me so far. Reset on initial upload. If you're compiling from code Joe, I can give you a few things that have helped me. None of the issues I've had end up being related to the base release firmware, instead all of my problems are a result of cheap boards not officially supported by the devs.

Thanks for your reply Norman.  I did factory reset the controller and I do not compile the code, just download and install.  I do use supported devices Dig-Octa's and Dig-Quads.  My problem is with Xlights crashing 5 minutes into the fpp connect upload to the controllers.  On the latest firmware, my 2400 pixel 8 channel Octa is only 30% loaded at the 5 minute mark.  I even tried it with ethernet instead of wifi and it didn't help much.

**Comment by noman1228** [comment]
Do you have WMM or any QOS setting on your router? Are you connected to the "show network" directly? The issue I was having was hardware related (from a hard head) and once I jumped through that hoop, networking was my problem. I would head over to the xlights forums for more help as I'm a complete hack that just refuses to spend $200 on a real controller, instead spending thousands of dollars and hundreds of hours making my idea work with Martin and Forkeneye's software.

**Comment by joe8012** [comment]
I'm using my test setup.  1 dig-octa, 1 dig-quad ae+8, RP4 player and home router.  I tried connecting ethernet from home router to dig-octa which is where my test megatree is setup.  It did not make a difference so I don't believe I have a network problem.  I have not had much success at the xlights page.  If I go back to ci-12059322379, I can get it to work.  I wanted to try the newer firmware because I am having some occasional flickering/control issues with my evo's on my megatree.

**Comment by MartinMueller2003** [comment]
The main issue is the access rate on the SD card. Unlike a PC, there is not a lot of buffering available to hold data while the SD is doing a write cycle.

**Comment by MartinMueller2003** [comment]
Still working on this.

**Comment by joe8012** [comment]
> Still working on this.

Thanks for all your work.  Just a note that I could not get the latest 4.0-ci12520549028 to upload a sequence to a single 50 pixel port on a dig-quad ae+ 8.  I flashed back to 4.0-ci12059322379 and fpp connect worked as expected.

**Comment by MartinMueller2003** [comment]
After some fixes, I just finished a 22 minute FPP Connect session in which 12 files were uploaded without any issues.
Experimental build on the web flasher has been updated
